"""Initial

Revision ID: 1ec0ea41fcd1
Revises: 
Create Date: 2020-06-03 15:07:41.821713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec0ea41fcd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('supervisor', sa.String(length=300), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_number')
    )
    op.create_table('meter_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_data_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meter_image')
    op.drop_table('meter_data')
    # ### end Alembic commands ###
