"""Added Foreign Keys

Revision ID: a72da92acfec
Revises: 1ec0ea41fcd1
Create Date: 2020-06-03 15:17:09.343192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72da92acfec'
down_revision = '1ec0ea41fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'meter_image', 'meter_data', ['meter_data_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meter_image', type_='foreignkey')
    # ### end Alembic commands ###
